framework:
  translator: ~

fos_user:
  db_driver: orm # other valid values are 'mongodb' and 'couchdb'
  firewall_name: main
  user_class: AppBundle\Entity\Membres
  from_email:
    address: "%ria.thas@gmail.com%"
    sender_name: "%ria.thas@gmail.com%"